# Data Containers

tmpdata:
  image: busybox:latest
  volumes:
    - /home
    - /Users/mattclark/.cos/cos/test/local.py:/code/mysite/local_settings.py
    - /Users/mattclark/.cos/cos/test/uwsgi.ini:/etc/uwsgi/uwsgi.ini
    - /etc/uwsgi
    - /tmp


# Service Containers

postgres:
  image: centerforopenscience/postgres:9.4
  environment:
    - POSTGRES_DB=cos_staging
  expose:
    - 5432
#  volumes_from:
#    - tmpdata

memcached:
  image: memcached:latest
  expose:
    - 11211


# Server Containers

web:
  # image: centerforopenscience/cos:latest
  build: .
  environment:
    - SOURCE_BRANCH=master
    # - SOURCE_REPO=https://github.com/ZobairAlijan/COS-Site.git
    # - SOURCE_REPO=https://github.com/icereval/cos-small.git
    - SOURCE_REPO=https://github.com/overstreetce/COS-Site.git
  ports:
    - 8000:8000
  expose:
    - 8000
  links:
    - postgres:postgres
    - memcached:memcached
  volumes_from:
    - tmpdata
